## Made by gendro_v ##

###############################################################################
## .___            .___.__           _________ __            .___.__         ##
## |   | ____    __| _/|__| ____    /   _____//  |_ __ __  __| _/|__| ____   ##
## |   |/    \  / __ | |  |/ __ \   \_____  \\   __\  |  \/ __ | |  |/  _ \  ##
## |   |   |  \/ /_/ | |  \  ___/   /        \|  | |  |  / /_/ | |  (  <_> ) ##
## |___|___|  /\____ | |__|\___  > /_______  /|__| |____/\____ | |__|\____/  ##
##          \/      \/         \/          \/                 \/             ##
###############################################################################

#################################################################

###############################################

###############################

#####################

###########

#####

#

########################
###### CUSTOM PART #####
########################

####	NAME	###

# Project name displayed

PROJECT		=	Indie Studio

# Binary name

NAME		=	indie_studio

####	PROG VARIABLE	###

CC		=	g++
RM		=	rm -f
MV		=	mv -f

IRRLICHT_NAME	=	./lib/irrlicht-1.8.3/lib/Linux/libIrrlicht.a

####	Dev Part	####

SRC		=	$(wildcard ./src/*.cpp)

IRRLICHT_SRC	=	C3DSMeshFileLoader.cpp			\
			CAnimatedMeshHalfLife.cpp		\
			CAnimatedMeshMD2.cpp			\
			CAnimatedMeshMD3.cpp			\
			CAnimatedMeshSceneNode.cpp		\
			CAttributes.cpp				\
			CB3DMeshFileLoader.cpp			\
			CBillboardSceneNode.cpp			\
			CBoneSceneNode.cpp			\
			CBSPMeshFileLoader.cpp			\
			CBurningShader_Raster_Reference.cpp	\
			CCameraSceneNode.cpp			\
			CCgMaterialRenderer.cpp			\
			CColladaFileLoader.cpp			\
			CColladaMeshWriter.cpp			\
			CColorConverter.cpp			\
			CCSMLoader.cpp				\
			CCubeSceneNode.cpp			\
			CD3D8Driver.cpp				\
			CD3D8NormalMapRenderer.cpp		\
			CD3D8ParallaxMapRenderer.cpp		\
			CD3D8ShaderMaterialRenderer.cpp		\
			CD3D8Texture.cpp			\
			CD3D9CgMaterialRenderer.cpp		\
			CD3D9Driver.cpp				\
			CD3D9HLSLMaterialRenderer.cpp		\
			CD3D9NormalMapRenderer.cpp		\
			CD3D9ParallaxMapRenderer.cpp		\
			CD3D9ShaderMaterialRenderer.cpp		\
			CD3D9Texture.cpp			\
			CDefaultGUIElementFactory.cpp		\
			CDefaultSceneNodeAnimatorFactory.cpp	\
			CDefaultSceneNodeFactory.cpp		\
			CDepthBuffer.cpp			\
			CDMFLoader.cpp				\
			CDummyTransformationSceneNode.cpp	\
			CEmptySceneNode.cpp			\
			CFileList.cpp				\
			CFileSystem.cpp				\
			CFPSCounter.cpp				\
			CGeometryCreator.cpp			\
			CGUIButton.cpp				\
			CGUICheckBox.cpp			\
			CGUIColorSelectDialog.cpp		\
			CGUIComboBox.cpp			\
			CGUIContextMenu.cpp			\
			CGUIEditBox.cpp				\
			CGUIEnvironment.cpp			\
			CGUIFileOpenDialog.cpp			\
			CGUIFont.cpp				\
			CGUIImage.cpp				\
			CGUIImageList.cpp			\
			CGUIInOutFader.cpp			\
			CGUIListBox.cpp				\
			CGUIMenu.cpp				\
			CGUIMeshViewer.cpp			\
			CGUIMessageBox.cpp			\
			CGUIModalScreen.cpp			\
			CGUIScrollBar.cpp			\
			CGUISkin.cpp				\
			CGUISpinBox.cpp				\
			CGUISpriteBank.cpp			\
			CGUIStaticText.cpp			\
			CGUITabControl.cpp			\
			CGUITable.cpp				\
			CGUIToolBar.cpp				\
			CGUITreeView.cpp			\
			CGUIWindow.cpp				\
			CImage.cpp				\
			CImageLoaderBMP.cpp			\
			CImageLoaderDDS.cpp			\
			CImageLoaderJPG.cpp			\
			CImageLoaderPCX.cpp			\
			CImageLoaderPNG.cpp			\
			CImageLoaderPPM.cpp			\
			CImageLoaderPSD.cpp			\
			CImageLoaderRGB.cpp			\
			CImageLoaderTGA.cpp			\
			CImageLoaderWAL.cpp			\
			CImageWriterBMP.cpp			\
			CImageWriterJPG.cpp			\
			CImageWriterPCX.cpp			\
			CImageWriterPNG.cpp			\
			CImageWriterPPM.cpp			\
			CImageWriterPSD.cpp			\
			CImageWriterTGA.cpp			\
			CIrrDeviceConsole.cpp			\
			CIrrDeviceFB.cpp			\
			CIrrDeviceLinux.cpp			\
			CIrrDeviceSDL.cpp			\
			CIrrDeviceStub.cpp			\
			CIrrDeviceWin32.cpp			\
			CIrrDeviceWinCE.cpp			\
			CIrrMeshFileLoader.cpp			\
			CIrrMeshWriter.cpp			\
			CLightSceneNode.cpp			\
			CLimitReadFile.cpp			\
			CLMTSMeshFileLoader.cpp			\
			CLogger.cpp				\
			CLWOMeshFileLoader.cpp			\
			CMD2MeshFileLoader.cpp			\
			CMD3MeshFileLoader.cpp			\
			CMemoryFile.cpp				\
			CMeshCache.cpp				\
			CMeshManipulator.cpp			\
			CMeshSceneNode.cpp			\
			CMetaTriangleSelector.cpp		\
			CMountPointReader.cpp			\
			CMS3DMeshFileLoader.cpp			\
			CMY3DMeshFileLoader.cpp			\
			CNPKReader.cpp				\
			CNullDriver.cpp				\
			COBJMeshFileLoader.cpp			\
			COBJMeshWriter.cpp			\
			COCTLoader.cpp				\
			COctreeSceneNode.cpp			\
			COctreeTriangleSelector.cpp		\
			COgreMeshFileLoader.cpp			\
			COpenGLCgMaterialRenderer.cpp		\
			COpenGLDriver.cpp			\
			COpenGLExtensionHandler.cpp		\
			COpenGLNormalMapRenderer.cpp		\
			COpenGLParallaxMapRenderer.cpp		\
			COpenGLShaderMaterialRenderer.cpp	\
			COpenGLSLMaterialRenderer.cpp		\
			COpenGLTexture.cpp			\
			COSOperator.cpp				\
			CPakReader.cpp				\
			CParticleAnimatedMeshSceneNodeEmitter.cpp	\
			CParticleAttractionAffector.cpp		\
			CParticleBoxEmitter.cpp			\
			CParticleCylinderEmitter.cpp		\
			CParticleFadeOutAffector.cpp		\
			CParticleGravityAffector.cpp		\
			CParticleMeshEmitter.cpp		\
			CParticlePointEmitter.cpp		\
			CParticleRingEmitter.cpp		\
			CParticleRotationAffector.cpp		\
			CParticleScaleAffector.cpp		\
			CParticleSphereEmitter.cpp		\
			CParticleSystemSceneNode.cpp		\
			CPLYMeshFileLoader.cpp			\
			CPLYMeshWriter.cpp			\
			CQ3LevelMesh.cpp			\
			CQuake3ShaderSceneNode.cpp		\
			CReadFile.cpp				\
			CSceneCollisionManager.cpp		\
			CSceneLoaderIrr.cpp			\
			CSceneManager.cpp			\
			CSceneNodeAnimatorCameraFPS.cpp		\
			CSceneNodeAnimatorCameraMaya.cpp	\
			CSceneNodeAnimatorCollisionResponse.cpp	\
			CSceneNodeAnimatorDelete.cpp		\
			CSceneNodeAnimatorFlyCircle.cpp		\
			CSceneNodeAnimatorFlyStraight.cpp	\
			CSceneNodeAnimatorFollowSpline.cpp	\
			CSceneNodeAnimatorRotation.cpp		\
			CSceneNodeAnimatorTexture.cpp		\
			CShadowVolumeSceneNode.cpp		\
			CSkinnedMesh.cpp			\
			CSkyBoxSceneNode.cpp			\
			CSkyDomeSceneNode.cpp			\
			CSMFMeshFileLoader.cpp			\
			CSoftwareDriver2.cpp			\
			CSoftwareDriver.cpp			\
			CSoftwareTexture2.cpp			\
			CSoftwareTexture.cpp			\
			CSphereSceneNode.cpp			\
			CSTLMeshFileLoader.cpp			\
			CSTLMeshWriter.cpp			\
			CTarReader.cpp				\
			CTerrainSceneNode.cpp			\
			CTerrainTriangleSelector.cpp		\
			CTextSceneNode.cpp			\
			CTRFlat.cpp				\
			CTRFlatWire.cpp				\
			CTRGouraud2.cpp				\
			CTRGouraudAlpha2.cpp			\
			CTRGouraudAlphaNoZ2.cpp			\
			CTRGouraud.cpp				\
			CTRGouraudWire.cpp			\
			CTriangleBBSelector.cpp			\
			CTriangleSelector.cpp			\
			CTRNormalMap.cpp			\
			CTRStencilShadow.cpp			\
			CTRTextureBlend.cpp			\
			CTRTextureDetailMap2.cpp		\
			CTRTextureFlat.cpp			\
			CTRTextureFlatWire.cpp			\
			CTRTextureGouraud2.cpp			\
			CTRTextureGouraudAdd2.cpp		\
			CTRTextureGouraudAdd.cpp		\
			CTRTextureGouraudAddNoZ2.cpp		\
			CTRTextureGouraudAlpha.cpp		\
			CTRTextureGouraudAlphaNoZ.cpp		\
			CTRTextureGouraud.cpp			\
			CTRTextureGouraudNoZ2.cpp		\
			CTRTextureGouraudNoZ.cpp		\
			CTRTextureGouraudVertexAlpha2.cpp	\
			CTRTextureGouraudWire.cpp		\
			CTRTextureLightMap2_Add.cpp		\
			CTRTextureLightMap2_M1.cpp		\
			CTRTextureLightMap2_M2.cpp		\
			CTRTextureLightMap2_M4.cpp		\
			CTRTextureLightMapGouraud2_M4.cpp	\
			CTRTextureWire2.cpp			\
			CVideoModeList.cpp			\
			CVolumeLightSceneNode.cpp		\
			CWADReader.cpp				\
			CWaterSurfaceSceneNode.cpp		\
			CWriteFile.cpp				\
			CXMeshFileLoader.cpp			\
			CXMLReader.cpp				\
			CXMLWriter.cpp				\
			CZBuffer.cpp				\
			CZipReader.cpp				\
			IBurningShader.cpp			\
			Irrlicht.cpp				\
			irrXML.cpp				\
			os.cpp

OBJ		=	$(SRC:.cpp=.o)

# Library directory(s) #

IRRLICHT_DIR	=	./lib/irrlicht-1.8.3/source/Irrlicht/

########	########
## End of custom part ##
########	########

# Flags

LDFLAGS = -L/usr/X11R6/lib$(LIBSELECT) -Llib/irrlicht-1.8.3/lib/Linux -lIrrlicht -lGL -lXxf86vm -lXext -lX11 -lXcursor

CPPFLAGS	+=	-W -Wall -Wextra -O3 -ffast-math -std=c++11 -w
CPPFLAGS	+=	$(LDFLAGS) $(IFLAGS)
LDFLAGS		+=	-L./lib/irrlicht-1.8.3/lib/Linux/ -lIrrlicht -lGL -lXxf86vm -lXext -lX11 -lXcursor
LDFLAGS		+=	-L/usr/X11R6/lib64/
IFLAGS		+=	-I. -I./header/ -I./lib/irrlicht-1.8.3/source/Irrlicht/
IFLAGS		+=	-I/usr/X11R6/include/ -I./lib/irrlich-1.8.3/include/
IFLAGS		+=	-Ilib/irrlicht-1.8.3/include

# Create Sources namefile
SRC_DIR		=	./src/
#SRC		=	$(foreach file, $(SRC_SRC), $(SRC_DIR)$(file))

#################
## COMPILATION ##
#################

## Settings ##

.SILENT :

.PHONY :	re all begin do_fclean fclean do_clean clean end file src

## Display rule ##

all :			first_time first $(NAME)

first :
		echo "#### $(PROJECT) ####"

## Compilation ##

compile_lib :		$(IRRLICHT_NAME)

$(NAME)		:	compile_lib $(OBJ)
			make -C ./makefile_src/
			./makefile_src/make_display "Compiling" $(SRC)
				$(CC) -o $(NAME) $(OBJ) $(CFLAGS) $(CPPFLAGS)
			echo -n "\n"

$(IRRLICHT_NAME) :
			make -C ./makefile_src/
			echo "#### Installing Irrlicht ####"
			make -C $(IRRLICHT_DIR)
			./makefile_src/make_display "Compiling" $(IRRLICHT_SRC)
			make fclean -C ./makefile_src/

## Clean ##

clean :			first do_clean

do_clean :
			make -C ./makefile_src/
			./makefile_src/make_display "Cleaning" $(SRC)
			make clean -C ./makefile_src/
			./makefile_src/make_display "Cleaning" $(IRRLICHT_SRC)
			rm -f ./lib/irrlicht-1.8.3/source/*.o
			$(RM) $(OBJ)

## Fclean ##

fclean :		first do_fclean

do_fclean :
			make -C ./makefile_src/
			./makefile_src/make_display "Cleaning" $(OBJ) $(NAME)
			$(RM) $(OBJ)
			$(RM) $(NAME)
			./makefile_src/make_display "Cleaning" $(IRRLICHT_SRC)
			./makefile_src/make_display "Cleaning" libirrlicht.a
			rm -f ./lib/irrlicht-1.8.3/source/Irrlicht/*.o
			rm -f $(IRRLICHT_NAME)
			make fclean -C ./makefile_src/

## Re ##

re :			first do_fclean compile_lib $(NAME)

## Install ##

install:		first compile_lib

## First ##

first_time :
			mkdir -p src
			mkdir -p header
			mkdir -p lib
			mkdir -p test
			mkdir -p info

#

#####

###########

#####################

###############################

###############################################

#################################################################
